name: CI                     # CI 파이프라인의 이름

on:                          # GitHub Actions 트리거
  push:
    branches: [ main ]        # main 브랜치에 푸시할 때 실행

jobs:
  build:
    runs-on: ubuntu-latest    # Ubuntu 환경에서 실행

    steps:                    # 각 단계들
      - uses: actions/checkout@v3   # 리포지토리의 코드 가져오기

      - uses: actions/setup-java@v3   # Java 설정
        with:
          distribution: 'openjdk'   # OpenJDK 사용
          java-version: '17'        # OpenJDK 17 사용

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew   # gradlew 실행 권한 부여

      - name: Build with Gradle
        run: ./gradlew clean build  # Gradle 빌드 명령어 실행