name: StackFlow-PJT CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: List project directory
        run: ls -alh

      - name: Grant execute permission for gradlew
        run: |
          cd ./BACK
          chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          cd ./BACK
          ./gradlew clean bootJar --exclude-task test

      - name: Check if JAR file exists
        run: ls -lh ./BACK/build/libs/

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }} \
            --push \
            -f ./BACK/Dockerfile ./BACK --progress=plain
            
      - name: Application Run
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Stopping existing container..."
            sudo docker kill ${{ secrets.PROJECT_NAME }} || true
            sudo docker rm -f ${{ secrets.PROJECT_NAME }} || true
      
            echo "Removing existing image..."
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }} || true
      
            echo "Running new container..."
            sudo docker run -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
              --name ${{ secrets.PROJECT_NAME }} \
              -d ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
      
            echo "Done"
